// Site search — fuzzy client-side search over the five investigative
// threads + Be Ready to Vote. Index is a static JSON file regenerated by
// scripts/build_index.py whenever content on those six pages changes.
(function () {
  var INDEX_URL = 'search-index.json';
  var fuse = null;
  var indexData = [];

  var overlay, panel, input, resultsEl, closeBtn, toggleButtons;
  var selectedIndex = -1;
  var currentResults = [];

  function buildOverlay() {
    overlay = document.createElement('div');
    overlay.className = 'search-overlay';
    overlay.innerHTML =
      '<div class="search-panel" role="dialog" aria-modal="true" aria-label="Search The La Palma Record">' +
        '<div class="search-input-row">' +
          '<svg viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="2"/><path d="M21 21l-4.3-4.3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>' +
          '<input type="text" class="search-input" placeholder="Search the record — a name, a date, a dollar figure…" autocomplete="off">' +
          '<button type="button" class="search-close">Esc</button>' +
        '</div>' +
        '<div class="search-results"><div class="search-hint">Search across Term Limits, Pension Debt, Leadership, Litigation, Transparency, and Be Ready to Vote.</div></div>' +
        '<div class="search-scope-note">Searching six pages — not Sources, About, or Contact.</div>' +
      '</div>';
    document.body.appendChild(overlay);
    panel = overlay.querySelector('.search-panel');
    input = overlay.querySelector('.search-input');
    resultsEl = overlay.querySelector('.search-results');
    closeBtn = overlay.querySelector('.search-close');

    overlay.addEventListener('click', function (e) {
      if (e.target === overlay) closeSearch();
    });
    closeBtn.addEventListener('click', closeSearch);
    input.addEventListener('input', function () { runSearch(input.value); });
    input.addEventListener('keydown', handleKeydown);
  }

  function openSearch() {
    overlay.classList.add('is-open');
    document.body.style.overflow = 'hidden';
    input.value = '';
    selectedIndex = -1;
    currentResults = [];
    resultsEl.innerHTML = '<div class="search-hint">Search across Term Limits, Pension Debt, Leadership, Litigation, Transparency, and Be Ready to Vote.</div>';
    window.setTimeout(function () { input.focus(); }, 30);
    loadIndexIfNeeded();
  }

  function closeSearch() {
    overlay.classList.remove('is-open');
    document.body.style.overflow = '';
  }

  function loadIndexIfNeeded() {
    if (fuse) return;
    fetch(INDEX_URL)
      .then(function (r) {
        if (!r.ok) throw new Error('search-index.json returned ' + r.status);
        return r.json();
      })
      .then(function (data) {
        indexData = data;
        fuse = new Fuse(data, {
          keys: [
            { name: 'title', weight: 0.4 },
            { name: 'snippet', weight: 0.35 },
            { name: 'meta', weight: 0.15 },
            { name: 'thread', weight: 0.1 },
          ],
          threshold: 0.34,
          ignoreLocation: true,
          minMatchCharLength: 2,
        });
        // The index may finish loading after the visitor has already
        // started typing (they'd have been shown "Loading…" in the
        // meantime) — re-run whatever query is currently in the box now
        // that Fuse is actually ready, so the result isn't stuck.
        if (input && input.value.trim().length >= 2) {
          runSearch(input.value);
        }
      })
      .catch(function (err) {
        resultsEl.innerHTML = '<div class="search-empty">Search is temporarily unavailable.</div>';
        if (window.console) console.error('Site search failed to load:', err);
      });
  }

  function escapeHtml(s) {
    return s.replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }

  function highlightMatches(text, query) {
    if (!query) return escapeHtml(text);
    var esc = escapeHtml(text);
    var words = query.split(/\s+/).filter(function (w) { return w.length > 1; });
    words.forEach(function (w) {
      var re = new RegExp('(' + w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'ig');
      esc = esc.replace(re, '<mark>$1</mark>');
    });
    return esc;
  }

  function runSearch(query) {
    selectedIndex = -1;
    if (!query || query.trim().length < 2) {
      currentResults = [];
      resultsEl.innerHTML = '<div class="search-hint">Search across Term Limits, Pension Debt, Leadership, Litigation, Transparency, and Be Ready to Vote.</div>';
      return;
    }
    if (!fuse) {
      resultsEl.innerHTML = '<div class="search-hint">Loading…</div>';
      return;
    }
    var results = fuse.search(query, { limit: 12 });
    currentResults = results.map(function (r) { return r.item; });

    if (!results.length) {
      resultsEl.innerHTML = '<div class="search-empty">No results for “' + escapeHtml(query) + '.” Try a name, a date, or a dollar figure.</div>';
      return;
    }

    resultsEl.innerHTML = results.map(function (r, i) {
      var item = r.item;
      var href = item.page + (item.anchor ? '#' + item.anchor : '');
      return (
        '<a class="search-result" href="' + href + '" data-idx="' + i + '">' +
          '<span class="search-result-icon">' + item.icon + '</span>' +
          '<span class="search-result-body">' +
            '<span class="search-result-thread">' + escapeHtml(item.thread) + (item.meta ? ' · ' + escapeHtml(item.meta) : '') + '</span>' +
            '<span class="search-result-title">' + highlightMatches(item.title, query) + '</span>' +
            '<span class="search-result-snippet">' + highlightMatches(item.snippet.slice(0, 140), query) + '</span>' +
          '</span>' +
        '</a>'
      );
    }).join('');
  }

  function handleKeydown(e) {
    var items = resultsEl.querySelectorAll('.search-result');
    if (e.key === 'Escape') {
      closeSearch();
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!items.length) return;
      selectedIndex = Math.min(selectedIndex + 1, items.length - 1);
      updateSelection(items);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (!items.length) return;
      selectedIndex = Math.max(selectedIndex - 1, 0);
      updateSelection(items);
    } else if (e.key === 'Enter') {
      if (selectedIndex >= 0 && items[selectedIndex]) {
        window.location.href = items[selectedIndex].getAttribute('href');
      } else if (items.length) {
        window.location.href = items[0].getAttribute('href');
      }
    }
  }

  function updateSelection(items) {
    items.forEach(function (el, i) {
      el.classList.toggle('is-selected', i === selectedIndex);
    });
    if (items[selectedIndex]) {
      items[selectedIndex].scrollIntoView({ block: 'nearest' });
    }
  }

  document.addEventListener('DOMContentLoaded', function () {
    buildOverlay();
    toggleButtons = document.querySelectorAll('[data-search-toggle]');
    toggleButtons.forEach(function (btn) {
      btn.addEventListener('click', openSearch);
    });
    document.addEventListener('keydown', function (e) {
      if ((e.key === '/' || (e.key === 'k' && (e.metaKey || e.ctrlKey))) &&
          document.activeElement.tagName !== 'INPUT' && document.activeElement.tagName !== 'TEXTAREA') {
        e.preventDefault();
        openSearch();
      }
    });
  });
})();
